kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]

[build]
command = "npm run build"
cwd = "./"
upload = { format = "directory", dir = "build/client" }

# Specify the build output directory for Pages
pages_build_output_dir = "build/client"

# Add compatibility date for Cloudflare Workers
compatibility_date = "2024-03-30"
